# Generated by Django 4.2.3 on 2023-08-04 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cart_Details', '0001_initial'),
        ('Payment_Details', '0002_payment_delete_payments'),
        ('customer_Details', '0004_alter_customers_user'),
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('order_Number', models.IntegerField()),
                ('order_Total', models.FloatField()),
                ('date', models.DateTimeField()),
                ('products', models.TextField()),
                ('payment_Options', models.CharField(max_length=20)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart_Details.cart')),
                ('custom', models.ManyToManyField(to='customer_Details.customers')),
                ('payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='Payment_Details.payment')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_shipment', to='Delivery.shipment')),
            ],
        ),
    ]
