# Generated by Django 4.2.1 on 2023-06-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_Number', models.IntegerField()),
                ('order_Total', models.FloatField()),
                ('customer', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('products', models.TextField()),
                ('payment_Options', models.CharField(max_length=20)),
            ],
        ),
    ]
