# Generated by Django 4.2.3 on 2023-07-07 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_Details', '0002_payment_delete_payments'),
        ('Order_Details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='Payment_Details.payment'),
        ),
    ]
