# Generated by Django 4.2.3 on 2023-08-12 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket',
        ),
    ]
