# Generated by Django 4.2.3 on 2023-07-14 05:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cart_Details', '0002_cart_product_remove_cart_products_cart_products'),
        ('customer_Details', '0004_alter_customers_user'),
        ('Delivery', '0001_initial'),
        ('Order_Details', '0002_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cart_Details.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='custom',
            field=models.ManyToManyField(to='customer_Details.customers'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(default= 1, on_delete=django.db.models.deletion.CASCADE, related_name='related_shipment', to='Delivery.shipment'),
            preserve_default=False,
        ),
    ]
