# Generated by Django 4.2.3 on 2023-08-04 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=32)),
                ('total', models.PositiveIntegerField()),
                ('number_of_products', models.PositiveIntegerField()),
                ('shipping_cost', models.FloatField()),
                ('payment_options', models.CharField(max_length=20)),
                ('discount', models.FloatField()),
                ('products', models.ManyToManyField(to='inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
