# Generated by Django 4.2.1 on 2023-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=32)),
                ('total', models.PositiveIntegerField()),
                ('number_of_products', models.PositiveIntegerField()),
                ('shipping_cost', models.FloatField()),
                ('payment_options', models.CharField(max_length=20)),
                ('discount', models.FloatField()),
            ],
        ),
    ]
