# Generated by Django 4.2.3 on 2023-08-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart_Details', '0002_alter_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='number_of_products',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
