# Generated by Django 4.2.3 on 2023-08-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart_Details', '0003_alter_cart_number_of_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
