# Generated by Django 4.2.3 on 2023-08-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart_Details', '0004_alter_cart_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
