# Generated by Django 4.2.3 on 2023-08-12 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Details', '0002_remove_order_basket'),
        ('Cart_Details', '0006_alter_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Order_Details.order'),
            preserve_default=False,
        ),
    ]
