# Generated by Django 4.2.3 on 2023-08-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart_Details', '0007_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
    ]
