# Generated by Django 4.2.3 on 2023-08-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_Details', '0006_remove_customers_user'),
        ('inventory', '0004_alter_product_image'),
        ('Ratings', '0002_alter_reviews_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='message',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='number_of_stars',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='sender',
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer_Details.customers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
