# Generated by Django 4.2.3 on 2023-07-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_Details', '0003_rename_name_vendor_store_name_vendor_vendor_name'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendor_Details.vendor'),
            preserve_default=False,
        ),
    ]
