# Generated by Django 4.2.3 on 2023-08-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_Details', '0005_customers_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='user',
        ),
    ]
