# Generated by Django 4.2.1 on 2023-06-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_Details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='store_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_Name',
        ),
    ]
