# Generated by Django 4.2.1 on 2023-06-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_Details', '0002_rename_store_name_vendor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='name',
            new_name='store_name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_Name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
