# Generated by Django 4.2.3 on 2023-08-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_Details', '0003_rename_name_vendor_store_name_vendor_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
